[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor = "#F63366"
backgroundColor = "black"
secondaryBackgroundColor = "#F0F0F0"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false

